// Pure token-generation logic for docs/<slug>/{tokens.json,llms.txt}, shared by
// app/scripts/generate-agent-docs.mjs (manual CLI run) and sandboxCheckpoint.js
// (the Design bible page's "Checkpoint & publish" button). No fs, no git — callers
// pass in the bible text they already have and get strings back.
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

// Token name -> { group, type }, matched by prefix. Order matters (first match wins).
const CATEGORIES = [
  { prefix: "color-", group: "color", type: "color" },
  { prefix: "space-", group: "space", type: "dimension" },
  { prefix: "radius-", group: "radius", type: "dimension" },
  { prefix: "duration-", group: "duration", type: "duration" },
  { prefix: "ease-", group: "ease", type: "cubicBezier" },
  { prefix: "size-", group: "size", type: "dimension" },
  { prefix: "font-", group: "font", type: "fontFamily" },
];

function categorize(name) {
  for (const c of CATEGORIES) {
    if (name.startsWith(c.prefix)) return { group: c.group, key: name.slice(c.prefix.length), type: c.type };
  }
  return { group: "other", key: name, type: "string" };
}

function cubicBezierArray(value) {
  const m = value.match(/cubic-bezier\(\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*\)/);
  return m ? m.slice(1, 5).map(Number) : null;
}

// Every ```css fenced block in the bible, read for --token: value; declarations.
export function readTokens(designMd) {
  const cssBlocks = [...designMd.matchAll(/```css\n([\s\S]*?)```/g)].map((m) => m[1]);
  const tokens = {};
  for (const block of cssBlocks) {
    for (const m of block.matchAll(/--([a-z0-9-]+):\s*([^;]+);/gi)) {
      const value = m[2].trim();
      if (value) tokens[m[1]] = value; // skip unset tokens like --font-ui: ;
    }
  }
  return tokens;
}

export function toDtcg(tokens) {
  const dtcg = {};
  for (const [name, value] of Object.entries(tokens)) {
    const { group, key, type } = categorize(name);
    dtcg[group] ??= {};
    if (type === "cubicBezier") {
      const arr = cubicBezierArray(value);
      dtcg[group][key] = arr ? { $value: arr, $type: "cubicBezier" } : { $value: value, $type: "string" };
    } else {
      dtcg[group][key] = { $value: value, $type: type };
    }
  }
  return dtcg;
}

export function buildLlmsTxt({ name, slug, repoSlug, tokenCount }) {
  const blobBase = repoSlug ? `https://github.com/${repoSlug}/blob/main` : null;
  const designMdLink = blobBase
    ? `[Design bible](${blobBase}/data/projects/${slug}/design.md)`
    : `Design bible: data/projects/${slug}/design.md`;
  const changelogLink = blobBase ? `[Changelog](${blobBase}/changelog.md)` : "Changelog: changelog.md";
  return `# ${name} design system

> Design system for ${name}, generated for coding agents from its agent-facing bible.
> The bible is the source of truth; tokens.json below is a machine-readable subset of it.

Generated ${new Date().toISOString().slice(0, 10)} — ${tokenCount} tokens.

## Docs

- ${designMdLink}: full agent-facing spec — principles, tokens, states, anti-patterns.
- [Tokens (DTCG)](./tokens.json): tokens in W3C Design Tokens Community Group format, generated from the bible.
- ${changelogLink}: dated history of system changes.

## Notes

- This file and tokens.json are generated by app/scripts/generate-agent-docs.mjs (CLI) or the Design bible page's Checkpoint & publish button. Do not hand-edit; regenerate instead.
- Only tokens the bible declares inside a fenced \`\`\`css block are included.
- If a value disagrees between the bible and the project's own token file, the token file wins per the bible's own rule — treat tokens.json as a convenience mirror, not a second source of truth.
`;
}

/** designMd text in, generated file contents out. Pure — caller does all fs/git work. */
export function generateDocs({ designMd, name, slug, repoSlug }) {
  const tokens = readTokens(designMd);
  const dtcg = toDtcg(tokens);
  const tokenCount = Object.keys(tokens).length;
  return {
    tokensJson: JSON.stringify(dtcg, null, 2) + "\n",
    llmsTxt: buildLlmsTxt({ name, slug, repoSlug, tokenCount }),
    tokenCount,
  };
}

export async function repoSlugFromGit(cwd) {
  try {
    const { stdout } = await execFileAsync("git", ["-C", cwd, "remote", "get-url", "origin"]);
    const m = stdout.trim().match(/github\.com[:/]([^/]+\/[^/]+?)(\.git)?$/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}
