import { canonicalColors, resolveDisplayColors, STARTER_COLORS, toCssVar } from "./tokens.js";

const EXPORT_KEYS = Object.keys(STARTER_COLORS);

export function slugify(name) {
  const slug = String(name || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return slug || "project";
}

export function uniqueSlug(project, taken) {
  const existing = String(project.slug || "");
  if (/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(existing) && !taken.has(existing)) {
    return existing;
  }
  const base = slugify(project.name);
  if (!taken.has(base)) return base;
  const short = String(project.id || "")
    .replace(/-/g, "")
    .slice(0, 8);
  const withId = short ? `${base}-${short}` : base;
  if (!taken.has(withId)) return withId;
  let n = 2;
  while (taken.has(`${base}-${n}`)) n += 1;
  return `${base}-${n}`;
}

export function assignSlugs(projects) {
  const taken = new Set();
  return projects.map((project) => {
    const slug = uniqueSlug(project, taken);
    taken.add(slug);
    return project.slug === slug ? project : { ...project, slug };
  });
}

export function compactTheme(colors) {
  const canon = canonicalColors(colors);
  const out = {};
  for (const key of EXPORT_KEYS) {
    if (canon[key]) out[key] = canon[key];
  }
  return out;
}

function cssBlock(selector, colors) {
  const compact = compactTheme(colors);
  const lines = Object.entries(compact).map(
    ([key, value]) => `  ${toCssVar(key)}: ${value};`
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

export function generateThemeCss(tokens) {
  return [
    "/* Generated by the design playground. Do not edit. */",
    "",
    cssBlock(":root", tokens?.dark || {}),
    "",
    cssBlock(".light", tokens?.light || {}),
    "",
  ].join("\n");
}

function mdCell(value) {
  return String(value || "—").replace(/\|/g, "\\|");
}

export function generateDesignMd(project, tokens) {
  const darkRows = resolveDisplayColors(tokens?.dark || {});
  const lightRows = resolveDisplayColors(tokens?.light || {});
  const lightById = Object.fromEntries(lightRows.map((row) => [row.id, row]));
  const table = [
    "| Role | Token | Dark | Light |",
    "|---|---|---|---|",
    ...darkRows.map((row) => {
      const light = lightById[row.id];
      return `| ${row.label} | \`${toCssVar(row.id)}\` | ${mdCell(row.value)} | ${mdCell(light?.value)} |`;
    }),
  ].join("\n");

  const source = project.tokenFile
    ? `\`${project.tokenFile}\``
    : "none";
  const repo =
    project.repoKind === "device" && project.localPath
      ? `device \`${project.localPath}\``
      : project.githubUrl
        ? `github ${project.githubUrl}`
        : "none";

  return [
    `# ${project.name || "Untitled"}`,
    "",
    "Generated by the design playground. Do not hand-edit.",
    "",
    `- Source: ${source}`,
    `- Repo: ${repo}`,
    `- Library: ${project.componentLibrary || "unset"}`,
    `- Mode: ${project.theme === "light" ? "light" : "dark"}`,
    "",
    "## Colorway",
    "",
    table,
    "",
    "## Theme",
    "",
    "```css",
    generateThemeCss(tokens).trim(),
    "```",
    "",
  ].join("\n");
}

export function projectMeta(project, slug) {
  return {
    id: project.id,
    slug,
    name: project.name || "Untitled",
    repoKind: project.repoKind || "github",
    githubUrl: project.githubUrl || "",
    localPath: project.localPath || "",
    tokenFile: project.tokenFile || "",
    tokenSource: project.tokenFile || project.tokenSource || null,
    theme: project.theme === "light" ? "light" : "dark",
    componentLibrary: project.componentLibrary || "",
    tokenLocks: project.tokenLocks || {},
    elementLocks: project.elementLocks || {},
    artifacts: project.artifacts || [],
    routes: project.routes || [],
  };
}
