import { canonicalColors, STARTER_COLORS, toCssVar } from "./tokens.js";

const EXPORT_KEYS = Object.keys(STARTER_COLORS);

export function compactTheme(colors, brandColors = []) {
  const canon = canonicalColors(colors);
  const out = {};
  const keys = [...EXPORT_KEYS, ...brandColors.map((color) => color.id)];
  for (const key of keys) {
    if (canon[key]) out[key] = canon[key];
  }
  return out;
}

function cssBlock(selector, colors, brandColors) {
  const compact = compactTheme(colors, brandColors);
  const lines = Object.entries(compact).map(
    ([key, value]) => `  ${toCssVar(key)}: ${value};`
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

export function generateThemeCss(tokens, brandColors = []) {
  return [
    "/* Generated by the design playground. Do not edit. */",
    "",
    cssBlock(":root", tokens?.dark || {}, brandColors),
    "",
    cssBlock(".light", tokens?.light || {}, brandColors),
    "",
  ].join("\n");
}

export { toCssVar };
