import { canonicalColors, STARTER_COLORS, toCssVar } from "./tokens.js";

const EXPORT_KEYS = Object.keys(STARTER_COLORS);

export function compactTheme(colors) {
  const canon = canonicalColors(colors);
  const out = {};
  for (const key of EXPORT_KEYS) {
    if (canon[key]) out[key] = canon[key];
  }
  return out;
}

function cssBlock(selector, colors) {
  const compact = compactTheme(colors);
  const lines = Object.entries(compact).map(
    ([key, value]) => `  ${toCssVar(key)}: ${value};`
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

export function generateThemeCss(tokens) {
  return [
    "/* Generated by the design playground. Do not edit. */",
    "",
    cssBlock(":root", tokens?.dark || {}),
    "",
    cssBlock(".light", tokens?.light || {}),
    "",
  ].join("\n");
}

export { toCssVar };
